### ISSUE TITLE
Results are not showing up on page

### ISSUE THREAD

**Issue by tkern** [Kaixhin/FGMachine#10]
Apologies if i have overlooked this too but I cannot get my results showing up anywhere on the web UI.
I haven't done anything complicated, just cloned FGMachine and FGLab. I can run an experiment against branin_noisy.py directly without fglab.py and i write the results to the correct directory (i think).

What did i do wrong?

`Output`

```
576129bb0df1c2b3e594acb7
|-- _notes.json
|-- _scores.json
|-- notes.json
|-- scores.json
`-- test.json
```

My folder structure:

```
experiments
|-- branin_noisy.py
|-- FGLab
|-- FGMachine
|---- projects.json  
```

`config.json` (for FGlab)

```
{
  "x": {
    "type": "float",
    "default": 2
  },
  "y": {
    "type": "float",
    "default": 7
  }
}
```

`projects.json`

```
{
    "57611f460df1c2b3e594ac9e": {
        "cwd": "/Users/user/Documents/programming/expriments/",
        "command": "python",
        "args": [
            "branin_noisy.py"
        ],
        "options": "double-dash",
        "capacity": 0.9,
    "results": "./"
    }
}
```

`branin_noisy.py`

```
import argparse
import json
import os

import numpy as np


def branin(x, y):
    return np.random.normal()


if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser(description='Calculate the Branin-Hoo function.')
    parser.add_argument('--x', dest='x', type=float, default=None)
    parser.add_argument('--y', dest='y', type=float, default=None)
    parser.add_argument('--_id', dest='_id', default=None)
    params = vars(parser.parse_args())

    # Evaluate function
    result = branin(params['x'], params['y'])
    print 'Result = %f' % result

    # Save result
    _id = params['_id']
    if not os.path.exists(_id):
        os.makedirs(_id)
    with open(os.path.join(_id, 'test.json'), 'w') as outfile:
        outfile.write(str(params))
    with open(os.path.join(_id, 'notes.json'), 'w') as outfile:
        outfile.write('{"_notes":"this is great","Notes":"even better"}')
    with open(os.path.join(_id, '_notes.json'), 'w') as outfile:
        outfile.write('{"_notes":"this is great","Notes":"even better"}')
    with open(os.path.join(_id, 'scores.json'), 'w') as outfile:
        json.dump({"_notes": "men",
                   '_scores': {'value': result}}, outfile)
    with open(os.path.join(_id, '_scores.json'), 'w') as outfile:
        json.dump({"_notes": "men",
                   '_scores': {'value': result}}, outfile)
```

**Comment by Kaixhin** [comment]
Hmm, firstly `projects.json` seems to have a typo (`expriments`):
`"cwd": "/Users/user/Documents/programming/expriments/"`. Secondly, according to [this section](https://github.com/Kaixhin/FGMachine#projects), if `results` is a relative path then it is relative to the FGMachine directory (since FGMachine spawns the experiment). So safest to use absolute paths. Otherwise I think it looks fine.

**Comment by tkern** [comment]
Kai, it is a typo which i made when creating the directory. Didn't want to change it when i noticed it:

```
(keras)--- programming/expriments » pwd
/Users/user/Documents/programming/expriments
```

I tried absolute paths `/Users/user/Documents/programming/expriments/` as well as  `/Users/user/Documents/programming/expriments/tmp`  as well as  `./`

The odd thing is that when i use absolute paths, it seems to ignore it. The python script can't create it because parameter `_id` is just the project ID. Hence i tried cwd being equal to results (absolute paths both) but that didn't work either.

**Comment by Kaixhin** [comment]
Because the experiments were finishing so quickly the folder watching wasn't being triggered properly. It should be able to handle that scenario now, and I've successfully tested with your code (using an absolute path) and the MNIST demo.
