### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by abojchevski** [Kaixhin/FGMachine#11]
When trying to run an FGMachine I get the following error:

```
Cannot GET /
```

I suspect it has to something with the hostname. To clarify I am trying to run both FGLab and FGMachine on the same machine. FGLab is working properly and I can create a project.

**Comment by Kaixhin** [comment]
Are you able to get the MNIST test example working when copying over `example.env` to `.env` for both FGLab and FGMachine? It does seem like a hostname/port problem. Can you provide more detail on where exactly in the workflow you get that error?

**Comment by abojchevski** [comment]
I haven't tried copying over `example.env` yet. I guess I am stuck at installing/running the FGMachine docker. To be clear here is what I do:
1. Run mongo docker with `sudo docker run -d --name mongodb mongo`
2. Run FGLab docker with `sudo docker run -d --name fglab --link mongodb:mongo -p 5080:5080 kaixhin/fglab`
3. Open `http://localhost:5080/` --> Works 
4. Run FGMachine docker with `sudo docker run -d --name fgmachine -h MY_PUBLIC_IP -v /var/run/docker.sock:/var/run/docker.sock -e FGLAB_URL=http://MY_PUBLIC_IP:5080/ -e FGMACHINE_URL=http://MY_PUBLIC_IP:5081/ -p 5081:5081 kaixhin/fgmachine`
   - Here i tried for using localhost, or MY_PUBLIC_IP, or my hostname
5. Open `http://localhost:5081/` --> Fails with the above error

Looking at the docker logs (`sudo docker logs fgmachine`) the following appears:

```
Server listening on port 5081
{ StatusCodeError: 404 - "Cannot POST //api/v1/machines\n"
    at new StatusCodeError (/root/FGMachine/node_modules/request-promise/lib/errors.js:32:15)
    at Request.RP$callback [as _callback] (/root/FGMachine/node_modules/request-promise/lib/rp.js:77:29)
    at Request.self.callback (/root/FGMachine/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/root/FGMachine/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/root/FGMachine/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - "Cannot POST //api/v1/machines\\n"',
  error: 'Cannot POST //api/v1/machines\n',
```

**Comment by abojchevski** [comment]
Additional info which I suspect might be the problem. In part of the logs there is the following snippet:

```
options: 
   { uri: 'http://MY_PUBLIC_IP:5080//api/v1/machines',
     method: 'POST',
```

Note the double slash `//api`. In browser `http://localhost:5080/api/v1/machines` works but this `http://localhost:5080//api/v1/machines` doesn't. I am not familiar with node.js enough to judge if this is a problem.

**Comment by Kaixhin** [comment]
Ah yep the problem looks like the extra `/` in the environment URLs - just remove it and it should be fine. Also, FGMachine doesn't have a web interface - just FGLab - so there is no `http://localhost:5081` to access anyway - which means your reported error isn't actually an error.

**Comment by abojchevski** [comment]
Removing the extra `/` was indeed the solution.
