### ISSUE TITLE
Error: "no machine capacity available" after failure to start project

### ISSUE THREAD

**Issue by tkern** [Kaixhin/FGMachine#12]
I create a new project. I add a machine to it by clicking the plus sign.
I go to "new experiment", leave the default values as is and Submit.

```
GET /projects/5788accd80d9e95117b34a51/capacity 200 81 - 0.488 ms
GET /projects/5788accd80d9e95117b34a51/capacity 200 81 - 0.127 ms
Error: Experiment could not start - please check projects.json
POST /projects/5788accd80d9e95117b34a51 200 304 - 6.653 ms
Reloaded projects
Projects registered with FGLab successfully
GET /projects/5788accd80d9e95117b34a51/capacity 501 33 - 0.917 ms
GET /projects/5788accd80d9e95117b34a51/capacity 501 33 - 0.431 ms
```

The error when i click submit again is:

> {"error":"No machine capacity available"}

I cloned both FGLab and Machine yesterday, ran the npm install scripts. My projects.json looks like this

```
{
    "5788accd80d9e95117b34a51": {
        "cwd": "/Users/thomaskern/Documents/programming/expriments/",
        "command": "python",
        "args": [
            "test.py"
        ],
        "options": "double-dash",
        "capacity": 1,
        "results": "/Users/thomaskern/Documents/programming/expriments/"
    }
}
```

The odd thing is, now it works again but I don't know why. I stopped FGMachine and deleted specs.json, I stopped fglab.

It seems very unreliable because I haven't yet figured out why this would happen at all and/or what it means, since capacity is there.

**Comment by Kaixhin** [comment]
It is a bit unreliable, and is generally triggered by experiments crashing, but might occur even if this isn't the case (hard to pinpoint though). As a workaround I've pushed some commits to FGLab and FGMachine which allow you to reset a given machine's capacity, and also made a note in the docs.
