### ISSUE TITLE
After Docker installation FGlab does not see FGMachine

### ISSUE THREAD

**Issue by iholas** [Kaixhin/FGMachine#16]
followed installation through Docker to install and run MongoDG, FGLab and FGMachine 
When I start the webUI no machine is available. Am I screwing up the URL for the machine? Tried both `my_ip:port` and `port:port` neither worked - thanks

**Comment by Kaixhin** [comment]
I just replicated this, and believe at some point one of the underlying libraries stopped translating addresses without a protocol (e.g. `1.2.3.4:5080`) to HTTP addresses - but explicitly adding the protocol (e.g. `http://1.2.3.4:5080`) for the FGMachine Docker commands seems to fix this. I've also updated the docs to reflect this.
