### ISSUE TITLE
Deleting FGMachine in web ui makes it impossible to register any FGMachine

### ISSUE THREAD

**Issue by tkern** [Kaixhin/FGMachine#9]
I got everything up and running, including running experiments.

My problem now is that I deleted the FGMachine by clicking the 'delete' button in the web ui. I have no idea how to register a machine now. I changed the port in .env in FGMachine but it doesn't show up in the UI.

Both FGLab and FGMachine are running the latest zipped release.

**Comment by Kaixhin** [comment]
Sorry if it wasn't clear in the docs, so I bolded [the notes](https://github.com/Kaixhin/FGMachine#option-1-local) about re-registering. To make it clearer that it can be dangerous, I've added confirm dialogues for deleting machines or projects with https://github.com/Kaixhin/FGLab/commit/4b1d10b9641a70d4a9e5a67812defd4d9a1d0e82.

**Comment by tkern** [comment]
Oh sorry, I really overlooked that bit. Thanks for the very quick feedback.
